services:
  
  # Database Service (MySQL)
  database:
    image: mysql:8
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - backend-network

  redis-service:
    image: redis:alpine
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - backend-network
    
  # Zookeeper Service
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend-network
  
  # Kafka Service

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend-network
    depends_on:
      - zookeeper

  # User Authentication Service
  user-auth:
    build:
      context: ./app/user-auth
    container_name: user-auth
    ports:
      - "4040:3050"  # Changed to avoid conflict
    environment:
      DATABASE_URL: mysql://user:user_password@database:3306/main_db
      REDIS_HOST: redis-service
      KAFKA_BROKER: kafka:9092
    depends_on:
      - database
      - redis-service
    networks:
      - backend-network
    volumes:
      - ./app/user-auth:/usr/src/app

  # User Function Service (Profile, Cart)
  user-function:
    build:
      context: ./app/user-function
    container_name: user-function
    ports:
      - "4050:3050"  # Changed to avoid conflict
    environment:
      DATABASE_URL: mysql://user:user_password@database:3306/main_db
      REDIS_HOST: redis-service
      KAFKA_BROKER: kafka:9092
    depends_on:
      - database
      - redis-service
    networks:
      - backend-network
    volumes:
      - ./app/user-function:/usr/src/app

  # Product Service
  product-service:
    build:
      context: ./app/product-service
    container_name: product-service
    ports:
      - "4020:3050"  # Changed to avoid conflict
    environment:
      DATABASE_URL: mysql://user:user_password@database:3306/main_db
      REDIS_HOST: redis-service
      KAFKA_BROKER: kafka:9092
    depends_on:
      - database
      - redis-service
    networks:
      - backend-network
    volumes:
      - ./app/product-service:/usr/src/app

  # Payment Service
  payment-service:
    build:
      context: ./app/payment-service
    container_name: payment-service
    ports:
      - "4010:3050"  # Changed to avoid conflict
    environment:
      DATABASE_URL: mysql://user:user_password@database:3306/main_db
      REDIS_HOST: redis-service
      KAFKA_BROKER: kafka:9092
    depends_on:
      - database
      - redis-service
    networks:
      - backend-network
    volumes:
      - ./app/payment-service:/usr/src/app

  notification-service:
    build:
      context: ./app/notification-service
    container_name: notification-service
    ports:
      - "4070:3050"  # Changed to avoid conflict
    environment:
      DATABASE_URL: mysql://user:user_password@database:3306/main_db
      REDIS_HOST: redis-service
      KAFKA_BROKER: kafka:9092
    depends_on:
      - database
      - redis-service
    networks:
      - backend-network
    volumes:
      - ./app/notification-service:/usr/src/app
    command: ["npm", "run", "dev"]

  # Nginx Reverse Proxy
  nginx:
    build: 
      context: ./app/nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - "3050:80"  # Expose port 3050 on the host
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-auth
      - user-function
      - product-service
      - payment-service
      - notification-service
    networks:
      - backend-network

volumes:
  database-data:

networks:
  backend-network:
    driver: bridge
